# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-03 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_client', '0001_initial'),
    ]

    #
    # This migration has been retrospectively cleared out, as it contained an
    # operation that led to application.client_secret being truncated
    # https://liv-it.atlassian.net/browse/TESLA-1469
    #
    operations = [
    ]
