---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: git
  pull: default
  image: plugins/git
  settings:
    recursive: true
    submodule_override:
      labsterutils: https://github.com/Livit/Livit.Learn.Utils.git
    tags: true


- name: test
  pull: default
  image: python:3.7.3-alpine3.8
  commands:
  - apk --update add bash curl git
  - scripts/cicd/test.sh
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  when:
    event:
    - push


- name: upload
  pull: default
  image: python:3.7.3-alpine3.8
  commands:
  - apk --update add bash curl
  - scripts/cicd/upload.sh reports
  environment:
    ARTIFACTS_SERVER:
      from_secret: artifacts_server
    ECR_ACCESS_KEY:
      from_secret: ecr_access_key
    ECR_SECRET_KEY:
      from_secret: ecr_secret_key
    GITHUB_TOKEN:
      from_secret: github_token
    S3_BUCKET:
      from_secret: s3_bucket
  when:
    event:
    - push
    status:
    - success
    - failure


services:
- name: postgres
  pull: default
  image: bitnami/postgresql:10.6.0
  environment:
    POSTGRES_DB: test
    POSTGRES_USER: postgres
  when:
    event:
    - push
...
